import { ArrowRight, Check, ShieldCheck } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

import { BrandIcon } from "@/features/marketing/components/BrandIcon";
import { frequentlyAskedQuestions, integrations } from "@/features/marketing/content/home";

export function HomeSections() {
  return <>
    <section className="koto-proof" data-koto-reveal aria-label="Principes de l’expérience Koto"><div className="koto-proof__stats"><div><strong>1</strong><span>question principale à la fois</span></div><div><strong>7 min</strong><span>durée cible de la consultation</span></div></div><div className="koto-proof__quote"><b>Principe produit</b><blockquote>« L’agence définit ce qu’elle veut savoir. Koto décide comment le découvrir. »</blockquote><span>Une délégation contrôlée, avec transition finale vers un humain.</span></div></section>

    <section className="koto-foundation" aria-labelledby="foundation-title"><div className="koto-section-heading koto-section-heading--center" data-koto-reveal><h2 id="foundation-title">La rigueur est une fondation.</h2><Link className="koto-outline-link" href="/contact">Voir une démonstration</Link></div><div className="koto-foundation__grid"><article data-koto-reveal><div><h3>Des garde-fous intégrés</h3><p>Le parcours recueille et structure le besoin sans promettre de stratégie, de prix ou de livrable.</p></div><div className="koto-foundation__image"><Image src="/images/product/koto-discovery-platform-light.webp" alt="Interface Koto avec progression et garde-fous de consultation" fill sizes="52vw" /></div></article><article data-koto-reveal><div><h3>Des décisions toujours explicables</h3><p>Chaque information conserve sa source et les zones à confirmer restent visibles pour votre équipe.</p></div><div className="koto-evidence-chart" aria-label="Graphique illustrant la qualité croissante du brief"><span>Contexte validé</span><i /><i /><i /><i /><i /><svg viewBox="0 0 500 180" role="img" aria-hidden="true"><path d="M0 170 C80 166 100 150 150 126 S230 110 270 84 S340 76 380 40 S440 36 500 2" fill="none" stroke="currentColor" strokeWidth="3" /></svg></div></article></div></section>

    <section className="koto-stories" id="cas-usage" aria-labelledby="stories-title"><div className="koto-section-heading koto-section-heading--center" data-koto-reveal><h2 id="stories-title">Conçu pour les échanges où le contexte compte.</h2></div><div className="koto-stories__grid"><article data-koto-reveal><Image src="/images/editorial/about-team.webp" alt="Équipe de services collaborant autour d’un dossier client" fill sizes="33vw" /><div><b>Services professionnels</b><strong>Un brief plus clair avant de mobiliser les spécialistes.</strong><Link href="/clients">Voir le cas d’usage <ArrowRight aria-hidden="true" /></Link></div></article><article data-koto-reveal><Image src="/images/editorial/methodology-table.webp" alt="Équipe préparant une méthodologie de découverte client" fill sizes="33vw" /><div><b>Agences</b><strong>Une qualification constante, même quand le volume augmente.</strong><Link href="/clients">Voir le cas d’usage <ArrowRight aria-hidden="true" /></Link></div></article><article data-koto-reveal><Image src="/images/editorial/blog-tools.webp" alt="Outils numériques utilisés dans un processus commercial" fill sizes="33vw" /><div><b>Opérations commerciales</b><strong>Le contexte circule sans nouvelle saisie.</strong><Link href="/clients">Voir le cas d’usage <ArrowRight aria-hidden="true" /></Link></div></article></div></section>

    <section className="koto-for" aria-labelledby="koto-for-title" data-koto-reveal><h2 id="koto-for-title">Koto pour</h2><div><strong>Agences marketing</strong><strong>Cabinets-conseils</strong><strong>Équipes de vente</strong><strong>Services B2B</strong></div><p>Préparez chaque premier échange avec le bon contexte. Qualifiez sans rigidité. Connectez le résultat aux outils déjà en place.</p></section>

    <section className="koto-integrations" id="integrations" data-koto-reveal aria-labelledby="integrations-title"><div><h2 id="integrations-title">Vos données client, enfin en mouvement.</h2></div><div><p>Koto est conçu pour synchroniser les données qualifiées avec votre CRM et déclencher des suivis simples dans les outils dont votre équipe dépend.</p><Link className="koto-outline-link" href="/contact">Parler de vos intégrations</Link></div><div className="koto-logo-marquee"><div className="koto-logo-marquee__track">{[...integrations, ...integrations].map(({ name, icon }, index) => <span key={`${name}-${index}`} title={name}><BrandIcon icon={icon} /><small>{name}</small></span>)}</div></div></section>

    <section className="koto-security" id="securite" data-koto-reveal aria-labelledby="security-title"><div className="koto-security__media"><Image src="/images/product/koto-discovery-platform-light.webp" alt="Interface Koto sécurisée montrant la progression d’une consultation" fill sizes="50vw" /><span><ShieldCheck aria-hidden="true" /> Garde-fous actifs</span></div><div className="koto-security__copy"><p className="koto-pill-label koto-pill-label--dark">Sécurité</p><h2 id="security-title">Votre sécurité est au cœur de Koto.</h2><p>Le prospect voit uniquement sa consultation. Vos règles, analyses et données internes restent réservées à votre équipe.</p><ul><li><Check aria-hidden="true" /> Accès par lien sécurisé</li><li><Check aria-hidden="true" /> Données internes séparées</li><li><Check aria-hidden="true" /> Décisions traçables</li></ul></div></section>

    <section className="koto-recognition" data-koto-reveal aria-labelledby="recognition-title"><p className="koto-pill-label">Principe fondateur</p><h2 id="recognition-title">« Une bonne consultation ne remplace pas l’expert. Elle lui donne enfin tout le contexte pour bien commencer. »</h2><span>Koto prépare la relation humaine, sans prendre sa place.</span><div className="koto-photo-marquee" aria-hidden="true"><div>{["about-team.webp", "methodology-table.webp", "blog-tools.webp", "about-team.webp", "methodology-table.webp", "blog-tools.webp"].map((image, index) => <Image key={`${image}-${index}`} src={`/images/editorial/${image}`} alt="" width={360} height={210} sizes="280px" />)}</div></div></section>

    <section className="koto-faq" data-koto-reveal aria-labelledby="faq-title"><div><p className="koto-pill-label">FAQ</p><h2 id="faq-title">Questions sur Koto?</h2></div><div className="koto-faq__list">{frequentlyAskedQuestions.map(([question, answer]) => <details key={question}><summary>{question}<span>⌄</span></summary><p>{answer}</p></details>)}</div></section>

    <section className="koto-final-wrap"><div className="koto-final-cta"><h2>Préparez de meilleurs échanges avant même le premier appel.</h2><div className="koto-action-row"><Link className="koto-button koto-button--mint" href="/contact">Demander une démo</Link><Link className="koto-button koto-button--outline" href="#fonctionnement">Explorer le produit</Link></div></div><div className="koto-final-stats"><div><strong>1</strong><span>question principale à la fois</span></div><div><strong>10–14</strong><span>questions au maximum</span></div><div><strong>3</strong><span>issues de qualification</span></div><div><strong>100%</strong><span>du jugement à votre équipe</span></div></div></section>
  </>;
}
